# Random Forest Analysis

```{r, warning=FALSE, message=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
library(tidyverse)
library(fossil)
library(randomForest)
options(scipen = 999) # No scientific notation
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
if (DATAPATH == "" ) stop( "Please add datapath to OAI_DATA" )

if(!exists('data_full')) {
  # LoadData must be in working directory
  source("OAI_LoadData.R", chdir = T) 
  data_full <- getCompleteData(DATAPATH, cluster_selection)
}
data_full <- na.omit(data_full)
clusters <- getClusterData(DATAPATH)
```

## Comparing 4 vs 5 Cluster - Rand Index

K4 vs K5 Comparison

```{r}
k4 <- clusters[,"K.4.Clusters"]
k5 <- clusters[,"K.5.Clusters"]
rand.index(k4, k5)
adj.rand.index(k4, k5)
remove(k4, k5)
```

## Recreating Random Forest Clusters

```{r splitData1}
knees <- data_full[which(as.numeric(data_full$EVNT) >= 4),]
knees$EVNT <- as.numeric(knees$EVNT) - 3

set.seed(1)
smp_size <- floor(5*nrow(knees)/6) # Five-fold
trn_ind <- sample(seq_len(nrow(knees)), size = smp_size, replace = F)
trn_data <- knees[trn_ind,]
tst_data <- knees[-trn_ind,]
```

### Only knee replacement data with ALL predictors:

```{r forestKneesFull}
rf_knees_all <- randomForest(as.factor(EVNT) ~  AGE + SEX + RACE_O + CEMPLOY_NW + MEDINS + PASE + WOMADL + WOMKP + WOMSTF + BMI + HEIGHT  + WEIGHT + COMORBSCORE + DPRSD + NSAID + NARC + P01OAGRD_Severe + P01OAGRD_Moderate + P01OAGRD_Mild + P01OAGRD_Possible  + P02JBMPCV_NEW_None + P02JBMPCV_NEW_One + EDCV_GradDeg + EDCV_UGDeg + EDCV_HSDeg+ V00WTMAXKG + V00WTMINKG + Surg_Inj_Hist, data=trn_data, proximity=TRUE, localImp = TRUE)
plot(rf_knees_all)
table(predict(rf_knees_all), trn_data$EVNT)
# getTree(rf_full, 1, labelVar = TRUE)
# importance(rf_full)
varImpPlot(rf_knees_all)
```

#### Only knee replacement data with BEST predictors

```{r forestKneesBest}
rf_knees_best <- randomForest(as.factor(EVNT) ~  AGE + SEX + RACE_O + PASE + WOMKP + WOMSTF +  HEIGHT  + WEIGHT + NSAID + P01OAGRD_Severe + P01OAGRD_Moderate + P01OAGRD_Mild + P01OAGRD_Possible  + EDCV_GradDeg + EDCV_UGDeg + EDCV_HSDeg+ V00WTMAXKG + Surg_Inj_Hist, data=trn_data, proximity=TRUE, localImp = TRUE)
plot(rf_knees_best)
table(predict(rf_knees_best), trn_data$EVNT)
# getTree(rf_full, 1, labelVar = TRUE)
# importance(rf_full)
varImpPlot(rf_knees_best)
```