---
title: "BS852 Class 6"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set working directory:
knitr::opts_knit$set(root.dir = "C:\\")

library(survival)
```

### Create variables
```{r}
match <- c()
for(i in 1:63){ match <- c(match, rep(i,2))}
disease <- rep( c(1,0), 63)                                  ## each pair has exposed/unexposed
exposed <- c(rep(c(1,1), 27),                                ## 27 pairs (D, E), (not D, E)
                        rep(c(1,0), 29),                     ## 29 pairs (D, E), (not D, not E)
                        rep(c(0,1), 3),                      ## 3 pairs (D, not E), (not D, E)
                        rep(c(0,0), 4))                      ## 4 pairs (D, not E), (not D, not E)
```

### Unconditional Model - INCORRECT
```{r}
mod <- glm(disease ~ exposed + factor(match), family = binomial)
summary(mod)
```

### Conditional Logistic Regression - CORRECT
```{r}
mod <- clogit(disease ~ exposed + strata(match))
summary(mod)
```


### Estrodat data
```{r}
## Read the data ##
estrodat <- read.csv("estrodat.csv", header=T, na.strings=".")
estrodat2 <- subset(estrodat, is.na(age)==F & is.na(gall)==F & is.na(hyper)==F 
                    & is.na(obesity)==F)
m.uni <- clogit(case ~ estro + strata(match), data = estrodat2)
summary(m.uni)
```

```{r}
m.multi <- clogit(case ~ estro + age + gall + hyper + obesity + strata(match), data = estrodat2)
summary(m.multi)
```

### Uninformative sets
```{r}
uninform.index <- c()
for (i in 1:length(unique(estrodat2$match))) {
  if (length(unique(estrodat2$case[ which(estrodat2$match==i)])) < 2) {
    uninform.index <- c(uninform.index, i)
  }
}
estrodat2[ which(estrodat2$match %in% uninform.index),]
```


```{r}
estrodat3 <- estrodat2[ -which(estrodat2$match %in% uninform.index),]
### Crude Analysis
m.uni2 <- clogit(case ~ estro + strata(match), data = estrodat3)
summary(m.uni2)
```

```{r}
m.multi2 <- clogit(case ~ estro + age + gall + hyper + obesity + strata(match),
data = estrodat3)
summary(m.multi2)
```

