---
title: 'BS852 Class 2: FHS data'
author: "Chunyu Liu"
date: ''
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls()) # clear environment

knitr::opts_knit$set(root.dir =  "C:\\Users\\BS_852\\classes\\BS852_Fall2020\\Class2")
```

### Load the 'epiR' package
```{r message=FALSE}
library(epiR)   # Load the 'epiR' package
```

### Assess Confounding and Interaction using FHS data
```{r } 

framdat2 <- read.table("/home/elkip/Datasets/framdat2.txt",header=T,sep="",na.strings=c("."))
head(framdat2)

### keep observations with a value for GLI
### select males
### select CHD=0 or CHD>4 (event after exam 4 or no event)
framdat2 <- framdat2[ which( !is.na(framdat2$GLI) & framdat2$SEX == 1 & (framdat2$CHD==0 | framdat2$CHD > 4)),]

### create age group variable - 4 groups
agegrp <- floor((framdat2$AGE-35)/10 + 1)

### create event indicator variable
chd_sw = (framdat2$CHD > 4)    ## TRUE is event, FALSE is no event

### create labels
chd_sw <- factor(chd_sw, levels = c(TRUE, FALSE), labels = c("Event", "No event"))
gli <- factor(framdat2$GLI, levels = c(1,0), labels = c("glucose intolerant", "Not glucose intolerant"))

```

### Format the data for epi.2by2 function
```{r } 

table(agegrp); table(gli); table(chd_sw)

fhs.data <- table(gli, chd_sw, agegrp)
fhs.data
   
```

### Analysis of association
```{r }
  res <- epi.2by2(dat = fhs.data, method = "cohort.count", conf.level = 0.95)
  res
  
  res$massoc$RR.strata.wald              # Stratum-specific Risk Ratios
  res$massoc$RR.crude.wald               # Crude Risk Ratio
  res$massoc$RR.mh.wald                  # MH adjusted Risk Ratio
  
  res$massoc$RR.homog.woolf              # Woolf test of homogeneity of RRs
  res$massoc$OR.homog.woolf              # Woolf test of homogeneity of ORs
  res$massoc$OR.homog.brday              # Breslow-Day test of homogeneity of ORs
              
  res$massoc$chisq.strata                # Stratum-specific association tests
  res$massoc$chisq.crude                 # Crude association test
  res$massoc$chisq.mh                    # MH adjusted association test
    
  res$massoc                             # Print all measures of association
 
  mantelhaen.test(fhs.data)              # MH adjusted association test
  mantelhaen.test(fhs.data, correct=F)   # Without continuity correction
```