---
title: "Homework Template"
author: "First Last"
date:   "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    theme: united
    code_folding: show
    toc: true
    style: BS831.css
    toc_float: true
---

## Settings

```{r settings, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

library(Biobase)
library(BS831)

OMPATH <- Sys.getenv("OMPATH")
if ( OMPATH=="" ) stop( "OMPATH must be set" )
print(OMPATH) 
DATA <- Sys.getenv("DATAPATH")
```

# Exercise 1: Creating an ExpressionSet from multiple parts

```{r}
EXP <- as.matrix(read.table(file.path(DATA, "hw1/ESet_exprs.xls"), sep = '\t', check.names = FALSE))
PDAT <- read.table(file.path(DATA, "hw1/ESet_pData.xls"), sep = '\t', header = TRUE)
FDAT <- read.table(file.path(DATA, "hw1/ESet_fData.xls"), sep = '\t', header = TRUE)

ESET <- ExpressionSet(assayData = EXP, phenoData = AnnotatedDataFrame(PDAT),
                               featureData = AnnotatedDataFrame(FDAT))

gMedian <- rowMedians(exprs(ESET))
sMedian <- rowMedians(t(exprs(ESET)))
```

```{r}
print(ESET)
```

```{r}
exprs(ESET)[1:5,1:5]
```

```{r}
head(gMedian)
```

```{r}
head(sMedian)
```
# Exercise 2: Median vs. MAD plot

```{r}
MED <- <compute median for each gene>
MAD <- <compute mad for each gene>

plot(MED,MAD,pch=20)
points(<top 100 genes coordinates>,pch=1,col='red')
legend(<topright legend with points annotations>)
```

```{r}
print(<top ten genes median and mad>)
```

Exercise 3: "Genotype" - Phenotype Association

```{r}
table(ESET$pam50)
```

# Exercise 4: Bayes Thereom

```{r}
ANS <- "A numeric value, i.e. the probability"
```

```{r}
print(ANS)
```
# Exercise 5: Matrix Operations

```{r}
set.seed(143)
X <- cbind(rep(1, 50), rnorm(50, 0, 1), rnorm(50, 0, 1))
y <- 3 + -4*X[,2] + 2*X[,3] + rnorm(50, 0, 1) # y = 3 + -4(x_1) + 2(x_2) + E
```

```{r}
BetaEstimator <- function(X, y){
  Beta <- matrix operations here using X and y
  return(Beta)
}
```

```{r}
BetaEstimator(X, y)
```